version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: tracer-web:v1
    environment:
      - PORT=8020
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1228
    env_file:
      - .env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    container_name: tracer-web

  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    command: -p 5432
    environment:
      - POSTGRES_PASSWORD=1228
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres_db

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 1228
    container_name: redis

volumes:
  staticfiles:
  postgres_data:
  redis_data:
