name: Build Docker container and push to DigitalOcean Container Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-django-job:
    uses: redcican/django-saas/.github/workflows/test-django.yaml@main
  docker-build:
    runs-on: ubuntu-latest
    needs: [test-django-job]
    steps:
    - uses: actions/checkout@v2
